#!/usr/bin/env node

/**
 * PostToolUse Enhancement: Log PR URL After Creation
 *
 * Captures and logs PR URL for easy access.
 */

const fs = require('fs');
const path = require('path');

// Get tool output from environment or stdin
const toolOutput = process.env.CLAUDE_TOOL_OUTPUT || '';

// Extract PR URL from gh pr create output
const prUrlMatch = toolOutput.match(/https:\/\/github\.com\/[^\s]+\/pull\/\d+/);

if (!prUrlMatch) {
  // No PR URL found, exit silently
  process.exit(0);
}

const prUrl = prUrlMatch[0];
const prNumber = prUrl.split('/').pop();

// Log to console
console.error(`[Hook] ✅ Pull Request created: ${prUrl}`);
console.error(`[Hook] Review command: gh pr view ${prNumber}`);

// Save to .claude/prs/ for reference
const projectRoot = process.env.PWD || process.cwd();
const prsDir = path.join(projectRoot, '.claude', 'prs');

if (fs.existsSync(path.join(projectRoot, '.claude'))) {
  if (!fs.existsSync(prsDir)) {
    fs.mkdirSync(prsDir, { recursive: true });
  }

  const now = new Date();
  const date = now.toISOString().slice(0, 10);
  const prFile = path.join(prsDir, `${date}-PR-${prNumber}.md`);

  const prInfo = `# Pull Request #${prNumber}

**URL**: ${prUrl}
**Created**: ${now.toISOString()}

## Quick Actions

\`\`\`bash
# View PR
gh pr view ${prNumber}

# Review changes
gh pr diff ${prNumber}

# Check status
gh pr checks ${prNumber}

# Merge PR
gh pr merge ${prNumber}
\`\`\`

---

*Auto-generated by log-pr-url hook*
`;

  try {
    fs.writeFileSync(prFile, prInfo, 'utf8');
    console.error(`[Hook] PR info saved: ${prFile}`);
  } catch {
    // Ignore write errors
  }
}

// Success
process.exit(0);
