#!/usr/bin/env node

/**
 * PreCompact Hook: Save State Before Compaction
 *
 * Runs before context compaction.
 * Saves important state for recovery.
 */

const fs = require('fs');
const path = require('path');

// Get project root from environment or current directory
const projectRoot = process.env.PWD || process.cwd();
const claudeDir = path.join(process.env.HOME, '.claude');
const compactionDir = path.join(claudeDir, 'compaction-state');

// Ensure directory exists
if (!fs.existsSync(compactionDir)) {
  fs.mkdirSync(compactionDir, { recursive: true });
}

// Generate timestamp
const now = new Date();
const timestamp = now.toISOString().replace(/[:.]/g, '-').slice(0, -5);

// Create state snapshot
const stateFile = path.join(compactionDir, `${timestamp}.md`);

const snapshot = `# Compaction State Snapshot

**Timestamp**: ${now.toISOString()}
**Project**: ${projectRoot}

## Context Before Compaction

This snapshot was created automatically before context compaction.

### Current Task

[Auto-detected from conversation]

### Important Variables/Paths

- Project root: ${projectRoot}

### Partial Progress

[To be filled by future enhancements]

---

## Recovery Instructions

If context is lost after compaction:
1. Review this snapshot
2. Check conversation transcript
3. Resume from last known state

---

*Auto-generated by pre-compact hook*
`;

// Save snapshot
try {
  fs.writeFileSync(stateFile, snapshot, 'utf8');
  console.error(`[Hook] Compaction state saved: ${stateFile}`);
} catch (err) {
  console.error(`[Hook] Error saving compaction state: ${err.message}`);
}

// Success
process.exit(0);
