#!/usr/bin/env node

/**
 * Stop Hook: Session End
 *
 * Runs when Claude Code session ends.
 * Extracts patterns and saves learnings.
 */

const fs = require('fs');
const path = require('path');

// Get project root from environment or current directory
const projectRoot = process.env.PWD || process.cwd();
const claudeDir = path.join(process.env.HOME, '.claude');
const sessionsDir = path.join(claudeDir, 'sessions');
const observationsFile = path.join(claudeDir, 'observations.jsonl');

// Ensure directories exist
if (!fs.existsSync(sessionsDir)) {
  fs.mkdirSync(sessionsDir, { recursive: true });
}

// Generate session filename
const now = new Date();
const timestamp = now.toISOString().replace(/[:.]/g, '-').slice(0, -5);
const date = now.toISOString().slice(0, 10);
const sessionFile = path.join(sessionsDir, `${date}-${timestamp.slice(11)}.md`);

// Accumulate Enterprise session cost into monthly budget file
let sessionCost = 0;
try {
  const stdin = fs.readFileSync(0, 'utf8');
  const data = JSON.parse(stdin);
  sessionCost = data.cost_usd || data.cost?.total_cost_usd || 0;
} catch (err) { /* no cost data available */ }

if (sessionCost > 0) {
  const budgetFile = path.join(claudeDir, 'budget.json');
  const thisMonth = now.toISOString().slice(0, 7); // YYYY-MM
  let budget = {};
  try { budget = JSON.parse(fs.readFileSync(budgetFile, 'utf8')); } catch (err) {}
  budget[thisMonth] = (budget[thisMonth] || 0) + sessionCost;
  try {
    fs.writeFileSync(budgetFile, JSON.stringify(budget, null, 2));
  } catch (err) {
    console.error(`[Hook] Error saving budget: ${err.message}`);
  }
}

// Get basic session info
const sessionInfo = {
  timestamp: now.toISOString(),
  project: projectRoot,
  duration: process.env.CLAUDE_SESSION_DURATION || 'unknown',
};

// Create session summary
const summary = `# Session Summary

**Date**: ${date}
**Time**: ${timestamp.slice(11)}
**Project**: ${projectRoot}
**Duration**: ${sessionInfo.duration}

## Session Notes

[Auto-generated session end summary]

This session has ended. Key observations will be extracted for continuous learning.

## Next Steps

- Review session transcript if needed
- Check for new instincts in \`.claude/instincts/\`
- Run \`/instinct-status\` to see learned patterns

---

*Auto-generated by session-end hook*
`;

// Save session summary
try {
  fs.writeFileSync(sessionFile, summary, 'utf8');
  console.error(`[Hook] Session summary saved: ${sessionFile}`);
} catch (err) {
  console.error(`[Hook] Error saving session summary: ${err.message}`);
}

// Append observation to JSONL for later analysis
const observation = {
  timestamp: now.toISOString(),
  project: projectRoot,
  type: 'session_end',
  sessionFile: sessionFile,
};

try {
  fs.appendFileSync(observationsFile, JSON.stringify(observation) + '\n', 'utf8');
} catch (err) {
  console.error(`[Hook] Error logging observation: ${err.message}`);
}

// Exit successfully
process.exit(0);
